export const PRINT_PAGE_WIDTH_IN = 6.125;
export const PRINT_PAGE_HEIGHT_IN = 9.25;
export const PRINT_PAGE_CONTENT_HEIGHT_IN = 8.625;

export const PREVIEW_INCH_TO_PX = 96;

const toPx = (inches: number) => Math.round(inches * PREVIEW_INCH_TO_PX);

export const PREVIEW_PAGE_WIDTH = toPx(PRINT_PAGE_WIDTH_IN);
export const PREVIEW_PAGE_HEIGHT = toPx(PRINT_PAGE_HEIGHT_IN);
export const PREVIEW_PAGE_CONTENT_HEIGHT = toPx(PRINT_PAGE_CONTENT_HEIGHT_IN);

export const PREVIEW_PAGE_PADDING_TOP = toPx(0.5);
export const PREVIEW_PAGE_PADDING_OUTER = toPx(0.5);
export const PREVIEW_PAGE_PADDING_INNER = toPx(0.65);
export const PREVIEW_PAGE_FOOTER_HEIGHT = PREVIEW_PAGE_HEIGHT - PREVIEW_PAGE_CONTENT_HEIGHT;

// Single shared cap for every chapter photo (all book versions).
// Must stay in sync with --chapter-photo-block-height in src/index.css.
export const PHOTO_BLOCK_HEIGHT_IN = 2.5;
export const PREVIEW_PHOTO_BLOCK_HEIGHT = toPx(PHOTO_BLOCK_HEIGHT_IN);

export const PREVIEW_PHOTO_HORIZONTAL_HEIGHT = PREVIEW_PHOTO_BLOCK_HEIGHT;
export const PREVIEW_PHOTO_VERTICAL_WIDTH = toPx(2.7);
export const PREVIEW_PHOTO_VERTICAL_HEIGHT = PREVIEW_PHOTO_BLOCK_HEIGHT;

export const PREVIEW_SPINE_WIDTH = toPx(0.125);
export const PREVIEW_SPINE_HALF_WIDTH = PREVIEW_SPINE_WIDTH / 2;
export const PREVIEW_SPREAD_HEIGHT = PREVIEW_PAGE_HEIGHT;
export const PREVIEW_SPREAD_WIDTH = PREVIEW_PAGE_WIDTH * 2 + PREVIEW_SPINE_WIDTH;

export const PREVIEW_SPREAD_COLUMN_GAP = PREVIEW_SPINE_WIDTH + PREVIEW_PAGE_PADDING_INNER * 2;

export const PREVIEW_MAX_VIEWPORT_WIDTH_RATIO = 0.94;
export const PREVIEW_MAX_VIEWPORT_HEIGHT_RATIO = 0.86;
